server:
  port: 8080  # HTTP를 위한 포트 설정
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kiosk.cz4ccgkg2r54.ap-northeast-2.rds.amazonaws.com:3306/kiosk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: csedbadmin
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true