server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      show_sql: false
      highlight_sql: true
  defer-datasource-initialization: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kiosk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: csedbadmin
  thymeleaf:
    cache: false