apiVersion: apps/v1
kind: Deployment
metadata:
  name: skala-app
  labels:
    app: skala-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skala-app
  template:
    metadata:
      labels:
        app: skala-app
    spec:
      containers:
      - name: skala-container
        image: amdp-registry.skala-ai.com/skala25a/sk008-my-app:1.0.kaniko-docker-24-71e497d5d193
        ports:
        - containerPort: 80
