apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk008-skala-app
  namespace: skala-practice
  labels:
    app: sk008-skala-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sk008-skala-app
  template:
    metadata:
      labels:
        app: sk008-skala-app
    spec:
      containers:
      - name: skala-container
        image: amdp-registry.skala-ai.com/skala25a/sk008-my-app:1.0.kaniko-docker-39-d4cd147b3af9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
          - configMapRef:
              name: skala-config
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          failureThreshold: 60
          periodSeconds: 10