apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skala-ingress
  namespace: skala-practice
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public-nginx
  rules:
    - host: sk008.skala25a.project.skala-ai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skala-service
                port:
                  number: 80