name: Deploy Spring Boot with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Gradle 실행 권한 부여
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # 3. Gradle 빌드
      - name: Build Project
        run: ./gradlew build

      # 4. 빌드 아티팩트 확인
      - name: Verify Build Artifacts
        run: ls -la build/libs/

      # 5. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-app:latest

      # 7. EC2로 배포
      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          KEY: ${{ secrets.DEPLOY_KEY }}
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/spring-app:latest
        run: |
          # SSH 설정
          mkdir -p ~/.ssh
          echo "$KEY" > deploy_key.pem
          chmod 400 deploy_key.pem
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          # EC2에 접속하여 Docker 설치 확인 및 실행
          ssh -i deploy_key.pem $USER@$HOST <<EOF
            # Docker 설치 확인 및 설치
            if ! [ -x "$(command -v docker)" ]; then
              echo "Docker not found, installing..."
              sudo yum update -y
              sudo yum install -y docker
              sudo service docker start
              sudo usermod -aG docker $USER
            fi

            # Docker 데몬 실행 확인
            if ! sudo systemctl is-active --quiet docker; then
              sudo service docker start
            fi

            # 기존 컨테이너 중지 및 삭제
            if [ $(docker ps -q --filter "name=spring-app") ]; then
              echo "Stopping existing container..."
              docker stop spring-app
              docker rm spring-app
            fi

            # 최신 이미지 가져오기 및 실행
            echo "Pulling latest Docker image..."
            docker pull $IMAGE_NAME
            echo "Running new container..."
            docker run -d --name spring-app -p 8080:8080 $IMAGE_NAME
          EOF